namespace TreeSitter.WpfSyntaxBox;

/// <summary>
/// Defines normalized syntax categories used by themes and formatting instructions.
/// </summary>
public enum HighlightKind : uint
{
    Keyword = 0,
    String = 1,
    Number = 2,
    Comment = 3,
    DocumentationComment = 4,
    Type = 5,
    BuiltinType = 6,
    Operator = 7,
    Bracket = 8,
    Delimiter = 9,
    Function = 10,
    Method = 11,
    Variable = 12,
    Property = 13,
    Constant = 14,
    Module = 15,
    Attribute = 16,
    Tag = 17,
    Boolean = 18,
    StringEscape = 19,
    StringSpecial = 20,
    StringRegex = 21,
    FunctionBuiltin = 22,
    FunctionMacro = 23,
    VariableBuiltin = 24,
    Parameter = 25,
    Label = 26,
    Error = 27,
    CommentTodo = 28,
    CommentNote = 29,
    CommentWarning = 30,
    CommentError = 31,
    MarkupHeading = 32,
    MarkupEmphasis = 33,
    MarkupLink = 34,
    MarkupList = 35,
    MarkupQuote = 36,
    MarkupRaw = 37,
    PunctuationSpecial = 38,
    TagAttribute = 39,
    TagDelimiter = 40,
}
